config:
  EMR_CLUSTER_NAME: "hail-spot-cluster" # Give a name to your EMR cluster
  EC2_NAME_TAG: "test-hail-EMR" # Adds a tag to the individual EC2 instances
  OWNER_TAG: "phenopolis" # EC2 owner tag
  PROJECT_TAG: "phenopolis-hail-test" # Project tag
  REGION: "eu-west-2"
  MASTER_INSTANCE_TYPE: "m4.large" # Suggested EC2 instances, change as desired
  WORKER_INSTANCE_TYPE: "r4.4xlarge" # Suggested EC2 instances, change as desired
  WORKER_COUNT: "1" # Number of worker nodes
  WORKER_BID_PRICE: "0.60" # Required for spot instances
  MASTER_HD_SIZE: "100" # Size in GB - For large data sets, more HD space may be required
  WORKER_HD_SIZE: "150" # Size in GB - For large data sets, more HD space may be required
  SUBNET_ID: "" # This field can be either left blank or for further security you can specify your private subnet ID in the form: subnet-1a2b3c4d
  S3_BUCKET: "s3n://hail-london-bucket/" # Specify your S3 bucket for EMR log storage, it must created first in S3 for the same REGION
  KEY_NAME: "london-hail" # Input your key name ONLY! DO NOT include the .pem extension
  PATH_TO_KEY: "/Users/alan/Dropbox/" # Full path to the FOLDER where the .pem file resides
  WORKER_SECURITY_GROUP: "sg-0e44ef720f58861a2" # Create a SG and set inbound rules for SSH (port 22) and Jupyter (port 8192) specific to your IP (MY IP option)
  MASTER_SECURITY_GROUP: "sg-0e44ef720f58861a2" # Create a SG and set inbound rules for SSH (port 22) and Jupyter (port 8192) specific to your IP (MY IP option)
  HAIL_VERSION: "current" # Specify a git hash version (the first 7-12 characters will suffice) to install a specific commit/version. When left empty or "current" will install the latest version of Hail available in the repo
